
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UniversityServiceBeanService", targetNamespace = "http://Service/", wsdlLocation = "http://localhost:8080/University-ejb/UniversityService?wsdl")
public class UniversityServiceBeanService
    extends Service
{

    private final static URL UNIVERSITYSERVICEBEANSERVICE_WSDL_LOCATION;
    private final static WebServiceException UNIVERSITYSERVICEBEANSERVICE_EXCEPTION;
    private final static QName UNIVERSITYSERVICEBEANSERVICE_QNAME = new QName("http://Service/", "UniversityServiceBeanService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/University-ejb/UniversityService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UNIVERSITYSERVICEBEANSERVICE_WSDL_LOCATION = url;
        UNIVERSITYSERVICEBEANSERVICE_EXCEPTION = e;
    }

    public UniversityServiceBeanService() {
        super(__getWsdlLocation(), UNIVERSITYSERVICEBEANSERVICE_QNAME);
    }

    public UniversityServiceBeanService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UNIVERSITYSERVICEBEANSERVICE_QNAME, features);
    }

    public UniversityServiceBeanService(URL wsdlLocation) {
        super(wsdlLocation, UNIVERSITYSERVICEBEANSERVICE_QNAME);
    }

    public UniversityServiceBeanService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UNIVERSITYSERVICEBEANSERVICE_QNAME, features);
    }

    public UniversityServiceBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UniversityServiceBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UniversityService
     */
    @WebEndpoint(name = "UniversityServicePort")
    public UniversityService getUniversityServicePort() {
        return super.getPort(new QName("http://Service/", "UniversityServicePort"), UniversityService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UniversityService
     */
    @WebEndpoint(name = "UniversityServicePort")
    public UniversityService getUniversityServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Service/", "UniversityServicePort"), UniversityService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UNIVERSITYSERVICEBEANSERVICE_EXCEPTION!= null) {
            throw UNIVERSITYSERVICEBEANSERVICE_EXCEPTION;
        }
        return UNIVERSITYSERVICEBEANSERVICE_WSDL_LOCATION;
    }

}
